sources:
  - name: source1
    schema: raw
    tables:
      - name: batch_claims_staging
      - name: streaming_claims_staging

models:
  - name: stg_allclaims
    columns:
      - name: claim_id
        tests:
          - not_null
          - unique
  - name: fct_claims
    description: "Transaction-level claims fact table"
    columns:
      - name: claim_id
        tests:
          - not_null
          - unique
      - name: claim_amount
        tests:
          - not_null
      - name: claim_date
      - name: claim_type
      - name: claim_status
      - name: trip_country
      - name: source_type
